### ISSUE TITLE
Cum nutrition gene？

### ISSUE THREAD

**Issue by shadow77215** [vegapnk/RJW-Genes#101]
Can you create a gene that can obtain more nutrients from cum? Just like the Robust Digestion gene in vanilla games, it only works on cum rather than raw food.

**Comment by vegapnk** [comment]
For Reference someone made a addon for [Cumpilation](https://github.com/vegapnk/Cumpilation):

```
https://gitgud.io/nazeeeem/nutritious-cum
Adds 2 things:
A bionic stomach that makes cum give more food when eaten, but any other food gives less. Also gives food over time when pawn is stuffed
A gene that does the same thing, but weaker and without the penalty. Also gives cumslut trait
```
