### ISSUE TITLE
Genitalia Size Genes behave wrong for growing up Children

### ISSUE THREAD

**Issue by vegapnk** [vegapnk/RJW-Genes#11]
Reported in #8, it seems that Genes changing genitalia size are not correctly applied to children. 

Aimed solution: 
Check on entering adult-life-stage, re-trigger genitalia size genes if necessary.

**Comment by Shabakur** [comment]
Issue seems to come from whenever a pawn changes size the updatesize function is triggered and resizes the genitalia/breasts/anus.
- https://gitgud.io/Ed86/rjw/-/blob/master/1.4/Source/Hediffs/Hediff_PartBaseNatural.cs
- https://gitgud.io/Ed86/rjw/-/blob/master/1.4/Source/Comps/CompRJWHediffBodyPart.cs
We could make sizechanging genes work through a harmonypatch and just make a prefix or transpiler. We could make the genes work like a multiplier, like larger size breast means breast are two times as large than they would have been normally.
