### ISSUE TITLE
chemical gene it doesn't work when was use by some  previous xenotype

### ISSUE THREAD

**Issue by taotaojzt** [vegapnk/RJW-Genes#117]
```
Could not load UnityEngine.Texture2D at UI/Icons/Genes/Chemicals/HormonalSerum/AddictionResistant in any active mod or in base resources.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.ContentFinder`1<UnityEngine.Texture2D>:Get (string,bool)
Verse.GeneDef:get_Icon ()
Verse.Widgets:DefIcon (UnityEngine.Rect,Verse.Def,Verse.ThingDef,single,Verse.ThingStyleDef,bool,System.Nullable`1<UnityEngine.Color>,UnityEngine.Material,System.Nullable`1<int>)
RimWorld.GeneUIUtility:DrawGeneBasics (Verse.GeneDef,UnityEngine.Rect,RimWorld.GeneType,bool,bool,bool)
RimWorld.GeneUIUtility:DrawGeneDef (Verse.GeneDef,UnityEngine.Rect,RimWorld.GeneType,System.Func`1<string>,bool,bool,bool)
f:b (Verse.GeneDef,bool,single&,single,single,UnityEngine.Rect,bool)
f:b (UnityEngine.Rect,System.Collections.Generic.List`1<Verse.GeneDef>,string,single&,single&,bool,UnityEngine.Rect,System.Nullable`1<bool>&)
f:DrawGenes (UnityEngine.Rect)
RimWorld.GeneCreationDialogBase:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
```

**Comment by vegapnk** [comment]
Hi @taotaojzt , 
thanks for your report. I think I know what you mean here, and I think I have the same issue. 
This happens when you scroll down the Genes to bottom? 

Can you do me one favour and try to load your game without RJW-Genes (but Licentialabs) and see if it still appears?

**Comment by taotaojzt** [comment]
yes, when i scroll down to bottom not just chemical gene disappear ,also some gene on bottom disappear with them

**Comment by vegapnk** [comment]
@taotaojzt  

![image](https://github.com/vegapnk/RJW-Genes/assets/104673111/878bc85a-8b77-46bc-91c7-e6782ed75524)

Does it look like this for you ? 

I do the following to get to this screen: 

1. Start a new Colony
2. Click further until you see colonists
3. edit xenotype
4. scroll down to dependencies

**Comment by taotaojzt** [comment]
![image](https://github.com/vegapnk/RJW-Genes/assets/126087365/fa690765-7db3-41b5-8c05-97eec981e869)

**Comment by taotaojzt** [comment]
![image](https://github.com/vegapnk/RJW-Genes/assets/126087365/07187e5b-abd6-4712-96c6-141a7ede301d)

**Comment by taotaojzt** [comment]
last two genes never work and also i found generous Donor gene it dosen't work

**Comment by vegapnk** [comment]
I am not 100% sure what your problem is, to be honest. 

If you get an error for the chemicals (your initial issue) once your scroll over them (my screenshot), that is not from my mod. 
I have the same error without my mod. 

The thing that is happening here is that the dependency genes (and immunity) are auto-generated for any drug. The licentia hormonal serum is a drug, but licentia does currently not provide images for the generated things. 
I could fix it, but if that is the (only) issue, it's not from RJW-Genes

**Comment by taotaojzt** [comment]
may i see your mod list?maybe i can found which mod  Incompatible with

**Comment by taotaojzt** [comment]
`ModsConfigData>
<version>1.5.4104 rev435</version>
<activeMods>
<li>zetrith.prepatcher</li>
<li>brrainz.harmony</li>
<li>bs.fishery</li>
<li>ludeon.rimworld</li>
<li>bs.betterlog</li>
<li>bs.performance</li>
<li>ludeon.rimworld.royalty</li>
<li>ludeon.rimworld.ideology</li>
<li>ludeon.rimworld.biotech</li>
<li>redmattis.betterprerequisites</li>
<li>vanillaexpanded.backgrounds</li>
<li>unlimitedhugs.hugslib</li>
<li>won.hair</li>
<li>won2.hair</li>
<li>jintuzilamian.hairstyle.afuwomenshairstyles</li>
<li>latta.fsharp.core</li>
<li>brrainz.achtung</li>
<li>rwzh.chinesepack.achtung</li>
<li>hydrologist.advancedbandnodes</li>
<li>zh.hydrologist.advancedbandnodes</li>
<li>meltup.advancedpowerplus</li>
<li>rwzh.chinesepack.advancedpowerplus</li>
<li>oskarpotocki.vanillafactionsexpanded.core</li>
<li>vanillaexpanded.vpsycastse</li>
<li>sarg.alphaanimals</li>
<li>qaq.qaaaq</li>
<li>sarg.alphabiomes</li>
<li>qa.qqijq</li>
<li>sarg.alphamechs</li>
<li>vanillaexpanded.vaeaccessories</li>
<li>oskarpotocki.vfe.empire</li>
<li>oskarpotocki.vfe.deserters</li>
<li>vanillaexpanded.vwe</li>
<li>vanillaexpanded.vwel</li>
<li>oskarpotocki.vfe.pirates</li>
<li>vanillaexpanded.vcef</li>
<li>vanillaexpanded.vcefaddon</li>
<li>vanillaexpanded.vwec</li>
<li>vanillaexpanded.vwehw</li>
<li>vanillaexpanded.vweq</li>
<li>vanillaexpanded.vweft</li>
<li>vanillaexpanded.vwenl</li>
<li>ceteam.combatextended</li>
<li>sarg.alphagenes</li>
<li>kitsune.alphagenes.lin.zh</li>
<li>zh.sarg.alphamechs</li>
<li>sarg.alphaprefabs</li>
<li>zh.sarg.alphaprefabs</li>
<li>aw.mech.helmets</li>
<li>akreedz.antiairweapon</li>
<li>tammybee.appearanceclothes</li>
<li>telardo.bettergenegraphicsframework</li>
<li>winds.bettermechanoidloot</li>
<li>zh.redmattis.betterprerequisites</li>
<li>biotexpans.core</li>
<li>telefonmast.graphicssettings</li>
<li>jecrell.jecstools</li>
<li>imranfish.xmlextensions</li>
<li>nals.facialanimation</li>
<li>nals.facialanimationexperimentals</li>
<li>erdelf.humanoidalienraces</li>
<li>redmattis.bigsmall.core</li>
<li>redmattis.bigsmall</li>
<li>redmattis.lamiasandothersnakes</li>
<li>redmattis.undead</li>
<li>zh.redmattis.undead</li>
<li>wzh.redmattis.bigsmall</li>
<li>smashphil.vehicleframework</li>
<li>3hstltd.framework</li>
<li>3hstltd.weapons.base</li>
<li>3hstltd.turrets.ii</li>
<li>eatkenny.leafzxg.dws.turretcollection</li>
<li>3hstltd.tcretex</li>
<li>3hstltd.weapons.jam</li>
<li>m00nl1ght.geologicallandforms</li>
<li>m00nl1ght.geologicallandforms.biometransitions</li>
<li>zh.biotexpans.core</li>
<li>biotexpans.mammalia</li>
<li>zh.biotexpans.mammalia</li>
<li>biotexpans.mythic</li>
<li>zh.biotexpans.mythic</li>
<li>8z.callforintel</li>
<li>brrainz.cameraplus</li>
<li>rwzh.chinesepack.cameraplus</li>
<li>mlie.capturethem</li>
<li>void.charactereditor</li>
<li>ceteam.combatextendedarmors</li>
<li>ceteam.combatextendedarmory</li>
<li>ceteam.combatextendedattachments</li>
<li>ceteam.combatextendedguns</li>
<li>ceteam.combatextendedmelee</li>
<li>lemontea.combatextendedzh</li>
<li>petetimessix.compacthediffs</li>
<li>zephyr.compacthediffszh</li>
<li>vk.compressedraid.latest</li>
<li>mei.compressedraid.zh</li>
<li>coldzero.craftableroyaltyweapons</li>
<li>zephyr.craftableroyaltyweaponszh</li>
<li>mlie.customprisonerinteractions</li>
<li>huppias.customprisonerinteractions.simplifiedchinese</li>
<li>dubwise.dubsbadhygiene</li>
<li>farxmai2.dbh.expanded</li>
<li>zh.farxmai2.dbh.expanded</li>
<li>merthsoft.designatorshapes</li>
<li>beibei.translationpack.designatorshapes</li>
<li>garwel.destroyitem</li>
<li>rwzh.chinesepack.destroyitem</li>
<li>latta.devl10n</li>
<li>latta.devl10n.zh</li>
<li>romyashi.dlwdframework</li>
<li>dubwise.dubsperformanceanalyzer.steam</li>
<li>dubwise.dubsperformanceanalyzer.cntrans</li>
<li>rwzh.chinesepack.dubsbadhygiene</li>
<li>dubwise.dubsmintmenus</li>
<li>rwzh.chinesepack.dubsmintmenus</li>
<li>dubwise.rimatomics</li>
<li>rwzh.chinesepack.rimatomics</li>
<li>pixelbirb.dwc</li>
<li>ebsg.sleep</li>
<li>vat.epoeforked</li>
<li>rwzh.leafzxg.epoeforked</li>
<li>vat.epoeforkedroyalty</li>
<li>rwzh.leafzxg.epoeforkedroyalty</li>
<li>statistno1.evolvedorgansredux</li>
<li>natsuki.evolvedorgansreduxzh</li>
<li>mlie.expandedroofing</li>
<li>keshash.extraexplosioneffects</li>
<li>kongkim.farmableneutroamine</li>
<li>fluffy.animaltab</li>
<li>fluffy.areaunlocker</li>
<li>fluffy.blueprints</li>
<li>rwzh.chinesepack.fluffy</li>
<li>vanillaexpanded.vfearchitect</li>
<li>vanillaexpanded.vfesecurity</li>
<li>aoba.fortress.industrial</li>
<li>aoba.fortress.industrial.citadel</li>
<li>aoba.fortress.medieval</li>
<li>tory187.rjw.gatheredrjw</li>
<li>redmattis.geneextractor</li>
<li>azzyh.redmattis.geneextractor.cn</li>
<li>danielwedemeyer.generipper</li>
<li>danielwedemeyer.generipper.zh</li>
<li>tac.genetrader</li>
<li>genetrader.zh</li>
<li>zh.m00nl1ght.geologicallandforms</li>
<li>xmb.giantautocannonturret.mo</li>
<li>xmb.gianturaniumslugturret.mo</li>
<li>gloomylynx.kotobike</li>
<li>tinygrox.chs.graphicssettings</li>
<li>turkler.gunpowder.preq</li>
<li>onslort.rjw.haremmastertrait</li>
<li>smuffle.harvestorganspostmortem</li>
<li>atomicgu.harvestorganspostmortemzh</li>
<li>rwzh.chinesepack.hugslib</li>
<li>rwzh.chinesepack.humanoidalienraces</li>
<li>lemontea.ratkincepatch</li>
<li>solaris.ratkinracemod</li>
<li>fxz.ratkin.facialanimation</li>
<li>yabbyshabby.imperialfunctionality</li>
<li>yabbyshabby.imperialfunctionality.zh</li>
<li>turnovus.biotech.integratedgenes</li>
<li>zh.biotech.integratedgenes</li>
<li>jaxe.bubbles</li>
<li>jaxe.bubbles.zh.hc</li>
<li>rwzh.leafzxg.jecstools</li>
<li>alias.degeneralizework</li>
<li>seioch.kurin.har</li>
<li>darkmiz.kurin.facialanimation</li>
<li>ninedaylongbow.chinesepack.kurinhar</li>
<li>lwm.deepstorage</li>
<li>rwzh.chinesepack.deepstorage</li>
<li>keshash.layeredwalldestruction</li>
<li>zed.0xff.loftbed</li>
<li>zh.loftbedbunkbeds</li>
<li>vanya.agent.lolidrophairshop</li>
<li>rs.lungemine</li>
<li>zylle.mapdesigner</li>
<li>m00nl1ght.mappreview</li>
<li>zh.m00nl1ght.mappreview</li>
<li>thereallemon.mapreroll</li>
<li>leafzxg.masterofcooking</li>
<li>leafzxg.masterofcrafting</li>
<li>windwardsnow.mechanitorweapons</li>
<li>scorpio.mechanoidfoundry</li>
<li>rwzh.chinesepack.vanillafactionsexpandedcore</li>
<li>asavikle.mechanoidfoundry.cn</li>
<li>gege.mechanoidmodifications</li>
<li>lanking.extended.mechmods</li>
<li>gege.mechanoidmodificationslevelandwork</li>
<li>lanking.trans.mechmods</li>
<li>kierannkkt.mechlordwarcasket</li>
<li>mlem.metaadjusternew</li>
<li>owlchemist.midsaversaver</li>
<li>cain.mineshaft</li>
<li>cain.mineshaft.cntrans</li>
<li>shaun.misccepatches</li>
<li>haplo.miscellaneous.core</li>
<li>haplo.miscellaneous.robots</li>
<li>leion247658.miscvhcraftablehrobots</li>
<li>zephyr.miscvhcraftablehrobotszh</li>
<li>alaestor.miscrobots.plusplus</li>
<li>haplo.miscellaneous.beesnhoney</li>
<li>haplo.miscellaneous.endgame</li>
<li>haplo.miscellaneous.incidents</li>
<li>haplo.miscellaneous.mapgenerator</li>
<li>haplo.miscellaneous.mapgenfactionbase</li>
<li>haplo.miscellaneous.mapgenerator.urban</li>
<li>haplo.miscellaneous.training</li>
<li>haplo.miscellaneous.turretbaseandobjects</li>
<li>haplo.miscellaneous.weaponrepair</li>
<li>rwzh.chinesepack.miscellaneous</li>
<li>bonible.modded.gun.sound.pack</li>
<li>mlie.proximity</li>
<li>vanillaexpanded.vfecore</li>
<li>vanillaexpanded.vfeart</li>
<li>vanillaexpanded.vfefarming</li>
<li>vanillaexpanded.vfepower</li>
<li>zal.morearchotechgarbage</li>
<li>sl4vp0wer.rimterritory</li>
<li>sl4vp0wer.mechtowers</li>
<li>zh.sl4vp0wer.mechtowers</li>
<li>wvc.sergkart.biotech.moremechanoidsworkmodes</li>
<li>moremechanoidsworkmodes.ru.zh</li>
<li>unofficial.morepracticaltraits</li>
<li>garryflowers.moreslaverystuff</li>
<li>zh.moreslaverystuff</li>
<li>teiwaz.mve</li>
<li>zh.new.solaris.ratkinracemod</li>
<li>winggar.noshadows</li>
<li>vesper.notmyfault</li>
<li>nuff.ceautopatcher</li>
<li>redundant.oopsallgenepacks</li>
<li>pzqaks.redundant.oopsallgenepacks.zh</li>
<li>peppsen.pmusic</li>
<li>taranchuk.performanceoptimizer</li>
<li>optimizer.zh</li>
<li>thomotron.phinix</li>
<li>rwzh.chinesepack.phinix</li>
<li>dsw.plant24handsetableschedule</li>
<li>rsmaintain.vanya.polarisbloc.mechenemy</li>
<li>vanya.polarisbloc.corelab.tmp</li>
<li>vanya.polarisbloc.securityforce.tmp</li>
<li>runningbugs.polarisblocsecurityforcedistresscallpatch</li>
<li>aoba.pregnator</li>
<li>mlie.pulsefireturret</li>
<li>wixun.pulsefireturret</li>
<li>ratys.bricksdontvanish</li>
<li>ratys.madskills</li>
<li>ratys.rtfuse</li>
<li>ratys.rtpowerswitch</li>
<li>ratys.rtsolarflareshield</li>
<li>rwzh.chinesepack.ratys</li>
<li>fxz.ratkinfaction</li>
<li>oark.ratkinfaction.oberoniaaurea</li>
<li>myde.aerocraftframework</li>
<li>oskarpotocki.vanillavehiclesexpanded</li>
<li>fxz.ratkinvehicle.morefailure</li>
<li>bbb.ratkinweapon.morefailure</li>
<li>huhu.ratkin.hair.kurinhar</li>
<li>mlie.rebound</li>
<li>lrb4.redmattisgenes.zh</li>
<li>uuugggg.replacestuff</li>
<li>garethp.replacestuffcompatibility</li>
<li>jaxe.rimhud</li>
<li>shouer.chinesepack.rimhud</li>
<li>dubwise.rimefeller</li>
<li>nomadrw.retextureandrestylerimefeller</li>
<li>rwzh.chinesepack.rimefeller</li>
<li>rimsenal.core</li>
<li>rimsenal.federation</li>
<li>wxty.addrimsenaltag</li>
<li>rimsenal.evp</li>
<li>rimsenal.feral</li>
<li>rimsenal.hair</li>
<li>rimsenal.security</li>
<li>rimsenal.storyteller</li>
<li>rwzh.chinesepack.rimsenal</li>
<li>mlie.rimworldspartanfoundry</li>
<li>mlie.spartanfoundrywarcraft</li>
<li>zh.rimworldspartanfoundry</li>
<li>telardo.romanceontherim</li>
<li>roolo.runandgun</li>
<li>smashphil.srtsexpanded</li>
<li>rwzh.chinesepack.srtsexpanded</li>
<li>blockdude.scrollablegizmos</li>
<li>memegoddess.searchanddestroy</li>
<li>vanillaexpanded.varme</li>
<li>vanillaexpanded.vfeproduction</li>
<li>vanillaexpanded.vmemese</li>
<li>shavius.vepatches</li>
<li>stm.shellabackgrounds</li>
<li>petetimessix.simplesidearms</li>
<li>syrus.simplesidearmsswitchweapon</li>
<li>pzqaks.simplesidearmsswitchweapon.zh</li>
<li>vanillaracesexpanded.highmate</li>
<li>vanillaracesexpanded.hussar</li>
<li>buyue.simpletexturetweaks</li>
<li>eundun.sparklingworldsce</li>
<li>albion.sparklingworlds.full</li>
<li>rwzh.leafzxg.sparklingworldsfull</li>
<li>jpt.speakup</li>
<li>zh.speakup</li>
<li>indeed.stackxxl</li>
<li>vis.staticquality</li>
<li>amaoto.straintacticsweapons</li>
<li>cryptidfarmer.stripper</li>
<li>jangodsoul.substanceabuse</li>
<li>zh.jangodsoul.substanceabuse</li>
<li>amaoto.thisthingsynthetik</li>
<li>zh.amaoto.thisthingsynthetik</li>
<li>ghxx.techadvancing</li>
<li>blackmarket420.taofc</li>
<li>zh.blackmarket420.taofc</li>
<li>aoba.deadmanswitch.core</li>
<li>aoba.wingsofpandora</li>
<li>gt.sam.tilledsoil</li>
<li>automatic.traderships</li>
<li>rwzh.leafzxg.traderships</li>
<li>localghost.transmog</li>
<li>unlimitedthreatscale.1trickpwnyta</li>
<li>hanami.chinesepack.unlimitedthreatscale.1trickpwnyta</li>
<li>unlimitedhugs.allowtool</li>
<li>unlimitedhugs.defensivepositions</li>
<li>rwzh.chinesepack.unlimitedhugs</li>
<li>shira.vaeapatch</li>
<li>syrchalis.processor.framework</li>
<li>3hstltd.berryexpanded</li>
<li>aoba.fortress.neolithic</li>
<li>oskarpotocki.vfe.tribals</li>
<li>zal.vfetmodpatches</li>
<li>tribeagle.vpsycastse.alienpatch</li>
<li>vanillaexpanded.vanillaanimalsexpanded</li>
<li>vanillaexpanded.vaeendandext</li>
<li>vanillaexpanded.vaeroy</li>
<li>rwzh.chinesepack.vae</li>
<li>vanillaexpanded.vappe</li>
<li>rwzh.chinesepack.vappe</li>
<li>rwzh.chinesepack.varme</li>
<li>zh.vanillaexpanded.backgrounds</li>
<li>vanillaexpanded.vanillabackstoriesexpanded</li>
<li>vanillaexpanded.vanillabackstoriesexpanded.zh</li>
<li>oskarpotocki.vanillaexpanded.ideologypatches</li>
<li>oskarpotocki.vanillaexpanded.royaltypatches</li>
<li>shavius.vfedeserters.zh</li>
<li>shavius.vfeempire.zh</li>
<li>zh.oskarpotocki.vfe.pirates</li>
<li>zh.oskarpotocki.vfe.tribals</li>
<li>puremj.mjrimmods.vanillafixhaulafterslaughter</li>
<li>vanillaexpanded.vfemedical</li>
<li>vanillaexpanded.vtexvariations</li>
<li>farxmai2.vanillafurnitureexpandedpack</li>
<li>zh.farxmai2.vanillafurnitureexpandedpack</li>
<li>vanillaexpanded.vfespacer</li>
<li>rwzh.chinesepack.vfe</li>
<li>hourai.vanillahairsretex</li>
<li>vanillaexpanded.ideo.dryads</li>
<li>vanillaexpanded.viehar</li>
<li>vanillaexpanded.ideo.relicsandartifacts</li>
<li>vanillaexpanded.viesas</li>
<li>shavius.vie.zh</li>
<li>vanillaexpanded.outposts</li>
<li>mlie.vanillaoutpostsexpandedexpandedranch</li>
<li>zh.vanillaexpanded.outposts</li>
<li>zh.clowncat.voee.ranch</li>
<li>mrhydralisk.voeadditionaloutposts</li>
<li>zh.mrhydralisk.voeadditionaloutposts</li>
<li>mrhydralisk.voedeliverylogistics</li>
<li>shavius.vpsye.zh</li>
<li>vanillaracesexpanded.customicons</li>
<li>red.vanillaracesexpanded.zh</li>
<li>oskarpotocki.vanillavehiclesexpandedtier3</li>
<li>shavius.vve.zh</li>
<li>hudsonriggs.vanillavehiclesexpandedtier39</li>
<li>vanillaexpanded.vee</li>
<li>rwzh.chinesepack.vanillaexpandedvee</li>
<li>rwzh.chinesepack.vcef</li>
<li>vanillaexpanded.vanillatraitsexpanded</li>
<li>rwzh.chinesepack.vanillatraitsexpanded</li>
<li>shavius.vehicleframework.zh</li>
<li>buyue.moremechanoidsworkmodes.zh</li>
<li>bbbbilly.wanderingsavage</li>
<li>mersid.wce2updated.core</li>
<li>rwzh.chinesepack.wce2core</li>
<li>weskermo.vpetweak</li>
<li>gguake.apparelbodyresolver</li>
<li>goudaquiche.moharframework</li>
<li>sutsutman.yrhentaiprime</li>
<li>savestoragesettings.kv.rw.fishtmp</li>
<li>nera.spawnthosegenes</li>
<li>oppey.eyegenes2</li>
<li>vanillaexpanded.vwetb</li>
<li>rwzh.chinesepack.vwe</li>
<li>carnysenpai.enableoversizedweapons</li>
<li>harkon.gunnut.core</li>
<li>harkon.gunnut.chapter1</li>
<li>harkon.gunnut.chapter2</li>
<li>harkon.gunnut.community</li>
<li>harkon.gunnut.deserttech</li>
<li>harkon.gunnut.fnscar</li>
<li>harkon.gunnut.krissvector</li>
<li>harkon.gunnut.ks23shotgun</li>
<li>harkon.gunnut.keltec</li>
<li>harkon.gunnut.sigsauerngsw</li>
<li>harkon.gunnut.ukrainianfirearms</li>
<li>zh.harkon.gunnut</li>
<li>derekbickley.ltocolonygroupsfinal</li>
<li>zh.ltocolonygroupsfinal</li>
<li>ladycookie.highmatecatearhair</li>
<li>lingluo.movesteamgeyser</li>
<li>mis.noface</li>
<li>pzqaks.processor.framework.zh</li>
<li>telkir.tmods.morefloors</li>
<li>telkir.tmods.morefloors.chinese</li>
<li>vk.twst.hair</li>
<li>xeonovadan.visiblepants</li>
<li>mlie.sdbridges</li>
<li>gha.zh.sdbridges</li>
<li>bitter.jn</li>
<li>pmhc.mod1</li>
<li>thearmyoffetidcorpses.cepatches</li>
<li>rim.job.world</li>
<li>akiya82.bprf</li>
<li>c0ffee.rjw.ideologyaddons</li>
<li>cof.moretorture</li>
<li>c0ffee.rimworld.animations</li>
<li>otyoty.sizedapparel</li>
<li>otyoty.sizedapparel.extended</li>
<li>chaeren.apparel</li>
<li>videnoir.chillrjw</li>
<li>vegapnk.multipleorgasm</li>
<li>abscon.privacy.please</li>
<li>euclideanandnil.crests</li>
<li>robtrg.rjwaditionalracepatches</li>
<li>rjw.sexperience.cumgenes</li>
<li>vegapnk.rjw.genes</li>
<li>rjw.sexperience</li>
<li>rjw.menstruation</li>
<li>shaba.rjw.more.genes</li>
<li>asmr.rjw.racesupport</li>
<li>c0ffee.rjw.events</li>
<li>rjw.ve_patches</li>
<li>stardust3d.rjw.patch.autopsy</li>
<li>pornault.rjwvanillastyleretexture</li>
<li>tory187.rjwanimaddons.sextra2</li>
<li>archersaiter.rjw.traits</li>
<li>rjw.cum</li>
<li>rjw.fb</li>
<li>rjw.fh</li>
<li>ed86.rjwia</li>
<li>lustlicentia.rjwlabs</li>
<li>shauaputa.rimnudeworldzoo</li>
<li>krkr.rocketman</li>
<li>rocketman.cn</li>
<li>akt.lewdclothes</li>
<li>euclidean.s16.core</li>
<li>winderig.processor</li>
<li>rjw.whoring</li>
<li>rjw.sexcultessentials</li>
<li>nyaamz.sa.alientextures</li>
<li>adk.sar.alien</li>
<li>otyoty.sizedapparel.head</li>
<li>teacher.uap</li>
<li>hawkeye32.hawks.anims</li>
</activeMods>
<knownExpansions>
<li>ludeon.rimworld</li>
<li>ludeon.rimworld.royalty</li>
<li>ludeon.rimworld.ideology</li>
<li>ludeon.rimworld.biotech</li>
</knownExpansions>
</ModsConfigData>`
this is my mod list

**Comment by taotaojzt** [comment]
![image](https://github.com/vegapnk/RJW-Genes/assets/126087365/5519e371-6996-4e50-b2c1-ed973cfeb41f)

**Comment by taotaojzt** [comment]
![image](https://github.com/vegapnk/RJW-Genes/assets/126087365/31def5d6-d327-4f99-8e0d-fc3dd6a6aa15)

**Comment by taotaojzt** [comment]
-<ModsConfigData>

<version>1.5.4104 rev435</version>


-<activeMods>

<li>zetrith.prepatcher</li>

<li>brrainz.harmony</li>

<li>bs.fishery</li>

<li>ludeon.rimworld</li>

<li>bs.performance</li>

<li>ludeon.rimworld.royalty</li>

<li>ludeon.rimworld.ideology</li>

<li>ludeon.rimworld.biotech</li>

<li>unlimitedhugs.hugslib</li>

<li>brrainz.cameraplus</li>

<li>rwzh.chinesepack.cameraplus</li>

<li>void.charactereditor</li>

<li>latta.fsharp.core</li>

<li>tory187.rjw.gatheredrjw</li>

<li>onslort.rjw.haremmastertrait</li>

<li>smuffle.harvestorganspostmortem</li>

<li>atomicgu.harvestorganspostmortemzh</li>

<li>rwzh.chinesepack.hugslib</li>

<li>nals.facialanimation</li>

<li>nals.facialanimationexperimentals</li>

<li>erdelf.humanoidalienraces</li>

<li>rwzh.chinesepack.humanoidalienraces</li>

<li>aoba.pregnator</li>

<li>jaxe.rimhud</li>

<li>shouer.chinesepack.rimhud</li>

<li>cryptidfarmer.stripper</li>

<li>gguake.apparelbodyresolver</li>

<li>sutsutman.yrhentaiprime</li>

<li>rim.job.world</li>

<li>akiya82.bprf</li>

<li>c0ffee.rjw.ideologyaddons</li>

<li>videnoir.chillrjw</li>

<li>vegapnk.multipleorgasm</li>

<li>abscon.privacy.please</li>

<li>euclideanandnil.crests</li>

<li>robtrg.rjwaditionalracepatches</li>

<li>rjw.sexperience.cumgenes</li>

<li>vegapnk.rjw.genes</li>

<li>rjw.sexperience</li>

<li>rjw.menstruation</li>

<li>asmr.rjw.racesupport</li>

<li>rjw.sexperience.ideology</li>

<li>stardust3d.rjw.patch.autopsy</li>

<li>c0ffee.rjw.events</li>

<li>pornault.rjwvanillastyleretexture</li>

<li>c0ffee.rimworld.animations</li>

<li>tory187.rjwanimaddons.sextra2</li>

<li>archersaiter.rjw.traits</li>

<li>rjw.cum</li>

<li>rjw.fb</li>

<li>rjw.fh</li>

<li>ed86.rjwia</li>

<li>lustlicentia.rjwlabs</li>

<li>shauaputa.rimnudeworldzoo</li>

<li>otyoty.sizedapparel</li>

<li>akt.lewdclothes</li>

<li>euclidean.s16.core</li>

<li>winderig.processor</li>

<li>rjw.whoring</li>

<li>rjw.sexcultessentials</li>

<li>nyaamz.sa.alientextures</li>

<li>otyoty.sizedapparel.head</li>

<li>otyoty.sizedapparel.extended</li>

<li>teacher.uap</li>

<li>hawkeye32.hawks.anims</li>

</activeMods>


-<knownExpansions>

<li>ludeon.rimworld</li>

<li>ludeon.rimworld.royalty</li>

<li>ludeon.rimworld.ideology</li>

<li>ludeon.rimworld.biotech</li>

</knownExpansions>

</ModsConfigData>
this time i just active few mods,bottom genes still disappear

**Comment by taotaojzt** [comment]
ok fix them, in the end this happen make me like a joker,it just outdate version and i rewrite version and i forget it, so sorry to waste your time
