### ISSUE TITLE
Errors related to BnS - Heaven and Hell and Licentia Labs

### ISSUE THREAD

**Issue by 73931** [vegapnk/RJW-Genes#122]
When using Big and Small - Heaven and Hell with RimJobWorld - Licentia Labs, a red error related to rjw_genes_elastic occurs on startup.
This is the error log when loading purely the dependencies of those mods.

```
Could not resolve cross-reference to Verse.GeneDef named rjw_genes_elastic (wanter=genes)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch5 (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.GeneDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList1<Verse.GeneDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_11<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

**Comment by vegapnk** [comment]
Thank you for your comment :) 
I hope this is addressed with 2.2.0, I will leave it open to keep an eye on it. 

It might also be an issue with the load order.

**Comment by 73931** [comment]
Unfortunately, it hasn't been fixed... The case of load order, BnS doesn't have any patches related to rjw, and BnS heaven and hell is just xenotype mods that combine genes from the original BnS, so I can't imagine why the error would only occur in those mods.

**Comment by RClef** [comment]
Found the issue. PatchBSHeavHell.xml calls for rjw_genes_elastic when patching Lil Glutton xenotype. The actual genedef is rjw_genes_elastic**ity**. It's a simple xml edit, so you can do it yourself while waiting for an official fix.
