### ISSUE TITLE
Males with the 'small breasts' gene also generate with breasts bigger than nipples

### ISSUE THREAD

**Issue by Dabestorange** [vegapnk/RJW-Genes#138]
I'm not too sure how to provide evidence as the game does not see this as an error, but it very much feels unintentional. Any male pawn with the 'small breasts' gene generates with breasts up to average size. The 'big breasts' gene does not do this and only affects female pawns, as the description says.

I am almost certain this is not an issue with a mod conflict, because I also tested it with no mods other than base RJW, Genes, and Sized Apparel.

Taking a look through the code myself to try and solve the issue, I noticed that the 'big breasts' gene file has a tag saying the pawn must be female, but the small 'breasts file' does not. Unfortunately, adding the line from the big breasts file to the small breasts file did not seem to fix anything, but I also know very little about coding so might have done something wrong.

The only gene the xenotype in the image below has is small breasts.
![image](https://github.com/user-attachments/assets/74637156-a6fe-4215-bc9b-ef88a51666dd)

**Comment by vegapnk** [comment]
Thank you for your report and the lovely image :) 

I will look into this. 

[Relevant File](https://github.com/vegapnk/RJW-Genes/blob/main/Source/Genes/GenitaliaSize/Gene_SmallBreasts.cs). Seems there is no check for `pawnShouldHaveBreasts`
