### ISSUE TITLE
Gene "Living Cum Bucket" causing stacks of 15,000 cum to be spawned.

### ISSUE THREAD

**Issue by b00marrows** [vegapnk/RJW-Genes#153]
The gene "living cum bucket" is spawning a stack of 15,000 cum when its spawned.
I posted a picture of it here:
https://www.loverslab.com/topic/110270-mod-rimjobworld/?do=findComment&comment=4456439

Conflict or not i dont know, but

**Comment by b00marrows** [comment]
This seems to have been due to the "severity" reaching 15000% (should this even be possible?)

How it reached that figure is the next guess. I am currently messing around with genes of the one who fills them up to see if its maybe "much cum" and/or generous donor for example.

**Comment by vegapnk** [comment]
Hi @b00marrows 

Yes this is ... intended ^^ at least right now. It's not a bug. If you blow them up so much, then they put out so much. 
I currently did not add an upper limit, but I will think about it.

**Comment by b00marrows** [comment]
Ah OK, that does make sense than.
So to figure out how the hell they got that full is the question.

I'm assuming its the combination of  "much cum" and "generous donor". Properly testing each would be the next goal next time i play.

While doing some (half conscious) testing last night i noticed the "output" of the gene is random, as in it happens randomly.
They can be doing anything and just start throwing up. In this case it kept happening while they where trying to breast feed.
Id prefer something a bit less intrusive on long important jobs.

Also does the slow drain (0.5/day?) do anything? like maybe make them a bit less hungry? Ill be honest while full of this much cum maybe hunger could be completely countered lol.

**Comment by b00marrows** [comment]
So played a bit last night with i think the update you released?
Seems the 2 with the gene where fine, there seems to be a "max" now.

I re-applied both "much cum" and "generous donor" to the other and the other 2 with the bucket gene still seemed to only fill to a normal amount.

As much as thats nice I'm still confused about how they reached such high numbers before. like a couple of hundred percent maybe but 15,000? Something cant be right about that.

Otherwise my only issue now is the random time of when they "eject" and how long it takes to do so.
By the description i would expect it to be intentional, when they want to and when they do its inside their control.
Maybe logically they would only "empty" themselves when they know they are going to get a new batch.

As of now it seems to be a weird delayed cum bucket function that applied a somewhat hefty negative to the pawn.
Maybe in conjunction with "cumflation" related genes it could have less/no negatives? (I forget are the cumflation genes yours?

Additionally I would really like it to be some "utalization" to the storing.
Like a sub-gene that allows them to utilize the stored cum for something like hunger.

I just want my little breeders happily wondering around doing busy work full of warm cum.

**Comment by vegapnk** [comment]
Preliminary Threshold added in 2.3.0, let's wait for feedback.
