### ISSUE TITLE
Multiple errors on startup with update 2.2.1

### ISSUE THREAD

**Issue by sir-plebeian** [vegapnk/RJW-Genes#156]
Not sure what is wrong, perhaps there is a mod requirement I am missing? But I just updated rjw genes to main branch 2.2.1 Release and I have a very long list of errors. Too long for me to list. I will attach the debug log from launch. 

My RJW modlist includes:
RJW
Sexperience
Sexperience Ideology
RJW Genes
RJW Events
Licentia Labs
RJW VE Highmate and Ideology patches

[Player.log](https://github.com/user-attachments/files/16747553/Player.log)

**Comment by prototype99** [comment]
that modlist.. is that in order? pretty sure licentia labs should be before rjw-genes

**Comment by sir-plebeian** [comment]
I do have it in that order. However, placing licentia labs before RJW Genes doesn't fix the errors I'm having. 

looking at the errors again they all are pretty similar: Genetic Diseases are all to load because it: 
-- "could not find type named RJW_Genes.GeneticDiseaseExtension from node"
-- "could not resolve cross-reference: No Verse.GenecategoryDef named rjw_genes_diseases found to give to Verse.GeneDef"
-- "Could not find type named RJW_Genes.HediffsCompProperties_ProcessCumbucketMTB from node"

**Comment by sir-plebeian** [comment]
after uninstalling and reinstalling, it started working. Not sure what error could have happened when I was just copy and pasting the zip folder...
