### ISSUE TITLE
No Twinkification Hediff applied on sexact by pawn with gene.

### ISSUE THREAD

**Issue by NickFejes** [vegapnk/RJW-Genes#174]
I am trying out the Twinkification Gene with a futa raider colony, and have noticed that my pawns with the Twinkification Gene are not applying the hediff to prisoners who are designated as comfort pawns.

I am not encountering any error messages in debug log, has anyone else encountered this? I can provide my full modlist if needed.

**Comment by vegapnk** [comment]
Hi @NickFejes , thanks for reaching out ! 

There are some things you can check: 

1.) The Twinkification should only work on males. Women (and futas for that regard) cannot be twinkified. 
2.) The sex must _finish_, i.E. the code for finishing sex must run
3.) You can enable the _RJW-Genes debug logging_ and check the log, and send that to me :) 

If there is really no debug log message, then the code is not even run 🤔  You should see a message along `{partner} got hediff {hediff.def.defName} from Patch_HediffIncreaseOnSex ({gene.def.defName}) upon sex with {pawn}`

**Comment by NickFejes** [comment]
As soon as i went back to test this to get you some debug logging. It started working perfectly. I have no idea what i did, i did install a new mod since then, so maybe it was a load order issue or some such.
