### ISSUE TITLE
Additional parts genes

### ISSUE THREAD

**Issue by Sairus323** [vegapnk/RJW-Genes#19]
I had an issue with additional breasts gene that if you edit pawns genome (i did through devmode/character editor though) with mentioned gene then the pawn gets one more row to the existing one. I guess (judging by the futanari gene report) same things most likely happen with additional penis gene.

**Comment by vegapnk** [comment]
Hey! 

Thanks for reporting. I don't use Character Editor, can you please elaborate? 

What I understand is the following: 

1. You have a new Pawn, no Gene(s)
2. You add the Extra Breast Gene
3. Pawn has 2 Pairs of Breasts
4. You Remove Breast Gene
5. Pawn has 2  Pairs of Breasts
6. You Add Breast Gene
7. Pawn has 3 Pairs of Breasts

**Comment by Sairus323** [comment]
1)i make pawn with additional breast gene along with other genes
2) pawn have 2 pairs of breasts
3)i edit genotype, changing other genes
4)pawn gets one more row, now having 3

**Comment by vegapnk** [comment]
Oh wow, will fix that. 👍
