### ISSUE TITLE
futa gene occasionally results in 2 penis pawns

### ISSUE THREAD

**Issue by malistaticy** [vegapnk/RJW-Genes#2]
even without the extra penis gene. 
i speculate its adding a penis to a female that was already generated as a futa?

**Comment by IDAZIZ** [comment]
when i only have the futa gene on, sometimes the penis doesn't generate

**Comment by vegapnk** [comment]
That could be the case ... 
Do you think that is funny or do you think I should add a short check for "which genitalia is already present"?
