### ISSUE TITLE
No genitalia swap by genes 

### ISSUE THREAD

**Issue by Sairus323** [vegapnk/RJW-Genes#21]
Not sure if thats RJW general problem or just your mod, but male and female genes don't change pawn genitals when applied using gene implanter.

I implanted genotype with the female gene to male pawn, now they are recognised by the game as female, but have penis and flat breasts...

**Comment by vegapnk** [comment]
Thanks for the feedback! 

I will look into it. It's a bit weird, because the code should cover it.

**Comment by vegapnk** [comment]
Sorry, I must say I cannot reproduce on 1.1.0. 

I did the following: 

- New Xenotype with "Female Only" and Gene Implanter
- Start new Colony, 2 males 1 Female with new Xenotype
- Use Implanter
- Pawns for me change gender and parts

**Comment by Sairus323** [comment]
Hmm... Weird... I just applied it around a hour ago and their parts did not change... I'll try again later and attach a log after gene installation if the problem will appear again

**Comment by Sairus323** [comment]
Tested. It seems something bugged for me back then. Everything works as it should now. Sorry for misinformation

**Comment by vegapnk** [comment]
(Seems fixed)
