### ISSUE TITLE
"Insect Breeder" gene interferes with fertilisation of egg-laying animals

### ISSUE THREAD

**Issue by Stretop** [vegapnk/RJW-Genes#23]
Steps to reproduce:

1) Allow bestiality and interspecies fertilisation in RJW settings.
2) Get a human-like male pawn with "Insect Breeder" gene.
3) Have it participate in a vaginal intercourse with a female egg-laying animal pawn (tortoise, snake, bird etc) with a non-fertilised egg.

Expected result:
Egg becomes fertilised.

Actual result:
Egg stays unfertilised.

Analysis:
When the very same pawn does the very same thing with the same animal after removing the gene (with devtools) - egg gets fertilised as expected. Both pawns are 100% fertile.

**Comment by vegapnk** [comment]
Good Morning, 
thanks for your report! 

Yes this is intended behavior. The current Gene-Implementation only checks when fucking humans if they have an egg inside. 
Animals are not checked, and it is ["hardcoded" for Insect-Eggs](https://github.com/vegapnk/RJW-Genes/blob/90204f913474fe86914a415dd982aeebad02b529/Source/Genes/Breeding/Patch_EggFertilization.cs#L88).

However, I like the idea of fertilizing the other eggs too, so I will add a new gene to the ToDo 👍

**Comment by Stretop** [comment]
I think there is a mix-up. I am not talking here about _insect eggs in animals_, I am talking here about animals' _own_ eggs (like chicken having chicken eggs, cobra having cobra eggs and so on).

The thing is, fertilisation of eggs here is not about checks for insect eggs (as _property of a vagina_) - it is about checks of an _egg-layer component_ of the animal itself. So normally it would not need any gene to work (and get those reptile/bird (not insect-parasitic) eggs fertilised); but "Insect Breeder" gene interferes with this default behaviour.

Funny additional thing: "Insect Breeder" gene _also_ interferes with breeding those insects who are not parasitic, like those, who have aedeagus/ovipore (and use the same standard "egglayer" comp as birds and reptiles) instead of parasitic "male/female ovipositor", so this needs to be mentioned in genes' descriptions too.

P.S. But yes, fertilising insect eggs inside animals (though not a subject of this particular bug) would also be nice.

**Comment by vegapnk** [comment]
Hmm, the thing is that ... my code does not touch anything? :D 

So prinicpally it is a Harmony Postfix, so all other logic is normally run before my code even starts, 
and then it really just looks for insect eggs.  If there are no insect eggs, the code just chills. 
I fear something else is causing your bug.

**Comment by Stretop** [comment]
No. I've just tested this again. Setup:
1) Using human-like male pawn and an ostrich female pawn.
2) Both are at 100% fertility. Ostrich has egg progress: 0.40%
3) Vaginal breeding

Without "Insect Breeder" gene:
Ostrich gets "egg progress: 0.40% Fertilised" after male human-like pawn orgasms.

With "Insect Breeder" gene:
Ostrich still has "egg progress: 0.40%" after male human-like pawn orgasms. No fertilisation.

It seems that this code chills too much, somehow preventing "normal" egg fertilisation from triggering =)

**Comment by Stretop** [comment]
Here is what happens when male pawn has the "Insect Breeder" gene (full RJW debug logging):

[RJW] Rimjobworld::impregnate(Vaginal):: MalePawn the Craftsman + emu:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW]  insect pregnancy
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.DoEgg_Patch0 (rjw.SexProps)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW] Rimjobworld::CanImpregnate checks (Vaginal):: MalePawn the Craftsman + emu:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.CanImpregnate_Patch0 (Verse.Pawn,Verse.Pawn,rjw.xxx/rjwSextype)
rjw.Quirk/<>c:<.cctor>b__48_5 (rjw.SexProps)
rjw.Quirk/<>c__DisplayClass42_0:<CountSatisfiedQuirks>b__0 (rjw.Quirk)
System.Linq.Enumerable/WhereListIterator`1<rjw.Quirk>:GetCount (bool)
System.Linq.Enumerable:Count<rjw.Quirk> (System.Collections.Generic.IEnumerable`1<rjw.Quirk>)
(wrapper dynamic-method) rjw.Quirk:rjw.Quirk.CountSatisfiedQuirks_Patch1 (rjw.SexProps)
(wrapper dynamic-method) rjw.SexUtility:rjw.SexUtility.SatisfyPersonal_Patch5 (rjw.SexProps,single)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW] Rimjobworld::CanImpregnate checks (Vaginal):: emu + MalePawn the Craftsman:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.CanImpregnate_Patch0 (Verse.Pawn,Verse.Pawn,rjw.xxx/rjwSextype)
RJW_Menstruation.CountSatisfiedQuirks_Patch:Postfix (int&,rjw.SexProps)
(wrapper dynamic-method) rjw.Quirk:rjw.Quirk.CountSatisfiedQuirks_Patch1 (rjw.SexProps)
(wrapper dynamic-method) rjw.SexUtility:rjw.SexUtility.SatisfyPersonal_Patch5 (rjw.SexProps,single)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

**Comment by Stretop** [comment]
And here is what happens when male pawn does not have the "Insect Breeder" gene (full RJW debug logging):

[RJW] Rimjobworld::impregnate(Vaginal):: MalePawn the Craftsman + emu:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW]  'normal' pregnancy checks
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW]  impregnate - by initiator
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW] Rimjobworld::CanImpregnate checks (Vaginal):: MalePawn the Craftsman + emu:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.CanImpregnate_Patch0 (Verse.Pawn,Verse.Pawn,rjw.xxx/rjwSextype)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW]  Doimpregnate MalePawn the Craftsman is a father, emu is a mother
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.DoImpregnate_Patch1 (Verse.Pawn,Verse.Pawn)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW]  Impregnation succeeded. Chance: 100%
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.DoImpregnate_Patch1 (Verse.Pawn,Verse.Pawn)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.impregnate_Patch2 (rjw.SexProps)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW] Rimjobworld::CanImpregnate checks (Vaginal):: MalePawn the Craftsman + emu:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.CanImpregnate_Patch0 (Verse.Pawn,Verse.Pawn,rjw.xxx/rjwSextype)
rjw.Quirk/<>c:<.cctor>b__48_5 (rjw.SexProps)
rjw.Quirk/<>c__DisplayClass42_0:<CountSatisfiedQuirks>b__0 (rjw.Quirk)
System.Linq.Enumerable/WhereListIterator`1<rjw.Quirk>:GetCount (bool)
System.Linq.Enumerable:Count<rjw.Quirk> (System.Collections.Generic.IEnumerable`1<rjw.Quirk>)
(wrapper dynamic-method) rjw.Quirk:rjw.Quirk.CountSatisfiedQuirks_Patch1 (rjw.SexProps)
(wrapper dynamic-method) rjw.SexUtility:rjw.SexUtility.SatisfyPersonal_Patch5 (rjw.SexProps,single)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

[RJW] Rimjobworld::CanImpregnate checks (Vaginal):: emu + MalePawn the Craftsman:
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
rjw.ModLog:Message (string)
(wrapper dynamic-method) rjw.PregnancyHelper:rjw.PregnancyHelper.CanImpregnate_Patch0 (Verse.Pawn,Verse.Pawn,rjw.xxx/rjwSextype)
RJW_Menstruation.CountSatisfiedQuirks_Patch:Postfix (int&,rjw.SexProps)
(wrapper dynamic-method) rjw.Quirk:rjw.Quirk.CountSatisfiedQuirks_Patch1 (rjw.SexProps)
(wrapper dynamic-method) rjw.SexUtility:rjw.SexUtility.SatisfyPersonal_Patch5 (rjw.SexProps,single)
rjw.JobDriver_Sex:Orgasm ()
(wrapper dynamic-method) rjw.JobDriver_Sex:rjw.JobDriver_Sex.SexTick_Patch2 (rjw.JobDriver_Sex,Verse.Pawn,Verse.Thing,bool,bool)
rjw.JobDriver_BestialityForMale/<>c__DisplayClass1_0:<MakeNewToils>b__6 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

**Comment by Stretop** [comment]
As you can see, "Insect Breeder" gene does not simply _**add**_ insect impregnation - it _**overrides**_ 'normal' impregnation with insect one. And this is unintended, I think.

**Comment by vegapnk** [comment]
I have to admit I can reproduce the bug. 
From my tests, there are many weird things happening. 

Wild Animal + No Genes = Fertilized
Wild Animal + Much Cum = Fertilized 
Wild Animal + Insect Breeder = Not Fertilized 
Tamed Animal + No Genes = Fertilized 
Tamed Animal + Much Cum = Not Fertilized (This makes absolutely no sense)
Tamed Animal + Insect Breeder = Not Fertilized 

I tested with a turkey, but I expect the same for all egg animals.
