### ISSUE TITLE
Fountain of Youth is a Fountain of Adulthood

### ISSUE THREAD

**Issue by PinkysBrain** [vegapnk/RJW-Genes#26]
```
var partnerAge = props.partner.ageTracker.AgeBiologicalTicks;
props.partner.ageTracker.AgeBiologicalTicks = Math.Max(MINIMUM_AGE, partnerAge - AGE_REDUCTION);
```
Should be something like
```
var partnerAge = props.partner.ageTracker.AgeBiologicalTicks;
If (partnerAge - AGE_REDUCTION > MINIMUM_AGE)
    props.partner.ageTracker.AgeBiologicalTicks = partnerAge - AGE_REDUCTION;
```

**Comment by vegapnk** [comment]
Hi, 

my code is fine. 
I fear you are a degenerate who changed the MInimum Age. 

Get some help.

**Comment by PinkysBrain** [comment]
If I decreased minimum age the code would just never trip and age down further.

The minimum age is 20 in your mod, so 18 yo skip straight to 20.

**Comment by vegapnk** [comment]
I will give you the benefit of the doubt and put the Min_Age to 18 and add activation-age also at 18.  
But I will not account for stuff like Races that "are adult with 10" etc.
