### ISSUE TITLE
Error on Game Load

### ISSUE THREAD

**Issue by AerosAtar** [vegapnk/RJW-Genes#5]
```
Could not resolve cross-reference to Verse.GeneDef named rjw_genes_human_genitalia (wanter=genes)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch6 (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.GeneDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.GeneDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```
Log: https://gist.github.com/HugsLibRecordKeeper/a07b431d626cdc57a88306929a817a0b

**Comment by vegapnk** [comment]
Thanks for reaching out! 

I think I know where this is coming from. I removed the "normal" genitalia (as they are somewhat redundant). 
Did you update to 1.0.X and had some xenotypes with that gene? 

Also, does the game ... still start and run?

**Comment by AerosAtar** [comment]
I use the lazy installer, so I'm always on the latest code from here.

I have no idea about the xenotypes, though I haven't created any of my own so I don't think so?

The game does run, though I am not sure if it could potentially cause issues down the line, and seeing errors is never fun. >.<

**Comment by vegapnk** [comment]
@AerosAtar I do not break things, don't worry :P 

Did the Errors appear again? All "good" so far? 

If you have errors, do they come on Game-Start, on Safe-Load or in the middle of the game?

**Comment by kaikaineeniak** [comment]
I have had a similar error occur at game start. This one seems to only occur if licentia labs is not loaded. I think there is a dependency on some licentia systems. Specifically related to cuminflation.

Could not resolve cross-reference to Verse.GeneDef named rjw_genes_likes_cumflation (wanter=genes)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.GeneDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.GeneDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by Shabakur** [comment]
Found the issue for rjw_genes_likes_cumflation error, [here](https://github.com/vegapnk/RJW-Genes/blob/main/Common/Patches/Xenotypes/GenitaliaUpdate.xml) under highmate we add rjw_genes_likes_cumflation, we should test if licentia labs is active before adding it.
