### ISSUE TITLE
eggs are not getting layed from the Hive Breeders

### ISSUE THREAD

**Issue by kinlass** [vegapnk/RJW-Genes#61]
So as the title state for some reason eggs are not actually coming out of the breeders. I will use the queen and put an egg into them but then no matter were the egg is it will just sit there after it has been fertilized. I have some colonists that will have 20-30 eggs. now if I kill them via character editor all 20-30 eggs hatch and I have 20-30 new colonist babies. 
![image](https://github.com/vegapnk/RJW-Genes/assets/144478747/2c2d7b6e-4fe5-4a3a-bd7a-54b307359687)

**Comment by kinlass** [comment]
I put it on 5% egg pregnancy speed and unfertilized eggs come out but not the fertilized one.

**Comment by vegapnk** [comment]
Thanks for reaching out !

I am not 100% sure if this is an issue, to be honest. 
Fertilized Eggs are not meant to come out - they are meant to stay in until they hatch.
Hatching will mean a "normal" birth. 

There is a bit of wackyness when it comes to egg-progress, but that is more of an upstream rjw issue, so maybe someone on the Discord can have another look. 

Let me know how things go
