### ISSUE TITLE
Gender Fluid change based on feminization and masculinization

### ISSUE THREAD

**Issue by IDAZIZ** [vegapnk/RJW-Genes#63]
rather than a 0.25 chance every 2 days that the pawn might change gender

i would love to have for example:
2 males fucking, the one getting fucked or raped will become more feminine, as a result his penis would shrink and his breasts would grow, and maybe his body shape would change too.
and the other male would have his penis get bigger or something.

same thing for females, the more you fuck a female the bigger her breasts would become, and if she has a thin body shape it would change to female body shape. 

i don't know about lesbians 😂

**Comment by IDAZIZ** [comment]
it sounds like a lot of code to make

**Comment by vegapnk** [comment]
Thanks for the idea :) 

I think for "this happens while normal sex" it's way to complicated - there are many things at play, including the sexdriver which will explode once the genitalia change (unless I have some time for an upstream change ...) 

But it might be a good candidate for an ability.
