### ISSUE TITLE
Issue with VE Malachai Patch

### ISSUE THREAD

**Issue by vegapnk** [vegapnk/RJW-Genes#68]
Follow up after 1.3.1 and #65, if I add the Malachai (without VE loaded): 
```xml
<li Class="PatchOperationFindMod">
  <mods>
    <li>Alpha Genes</li>
  </mods>
  <match Class="PatchOperationAdd">
     <xpath>Defs/XenotypeDef[defName="AG_Malachai"]/genes</xpath>
       <value>
	  <li>rjw_genes_demonic_genitalia</li>
       </value>
  </match>
</li>
```

Then I get the following 

```
[RJW Genes] Patch operation Verse.PatchOperationSequence(count=9, lastFailedOperation=Verse.PatchOperationFindMod(Alpha Genes)) failed
file: C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\rjw-genes\Common\Patches\Xenotypes\PatchAlphaGenes.xml
```

Likely issue is that I will need 2 mods to look for in the PatchOperation ...

**Comment by Stars22223** [comment]
This is why you don't copy the code of someone who doesn't know how to mod Rimworld, lol
should there also have been <li>Vanilla Races Expanded - Sanguophage</li> under <mods>?
sorry for that
