### ISSUE TITLE
Patch operation error on startup (when Sexperience is not enabled?) 

### ISSUE THREAD

**Issue by mwcrow** [vegapnk/RJW-Genes#69]
RJW-Genes generates a patching operation error on game start. I assume this is caused by lack of Sexperience mod: 

```
[RJW Genes] Patch operation Verse.PatchOperationConditional(Defs/ThingDef[defName="GatheredCum"]/ingestible/outcomeDoers) failed
file: C:\Program Files (x86)\GOG Galaxy\Games\RimWorld\Mods\rjw-genes\Common\Patches\ThingDefs\Sexperience_Cum.xml 
```

**Comment by mwcrow** [comment]
Sadly, I don't know the patching syntax well enough to know how to add optional mod dependency to a patch that already has different conditional operation class :<

**Comment by vegapnk** [comment]
Hmm, I can reproduce. Sorry for the inconvenience. 

But why does not everybody play with the same mods that I do?? smh.
