### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Stars22223** [vegapnk/RJW-Genes#70]
Please consider:
1. Adding the info about conflicting mods into About.xml, so that we can see it in RimPy.
2. Disabling any xenotypes and genes this mod adds, if they're unplayable or broken without 3rd party mods. Cum genes, for example. Any xenos using "fertilin'" should also be disabled if you don't have Sexperience, as there's no way to gain this fertilin' otherwise. I don't want to add Sexperience, Licentia or any of the RJW addons, as I find them unrealistic, broken or bloated or all three of those. I don't really understand how the insect xenos this mod adds work without Alpha Genes either (despite their seeming integration with AG, I'm not seeing any eggs genes?), but that part is whatever.
3. If it's even possible, disabling conflicting RJW options by default, like those for animal inheritance, or adding a better description about what exactly should be disabled in the front page.

Additionally:
1. The mod patches VE Phytokin xenotypes, but not their "female only" gene. Is this intended? (Since you mentioned other male/female only genes caused issues).
2. The "hypersexual" trait from RJW has been broken for years now. It disables the recreation and psyfocus gain from types of meditation other than sex, but doesn't actually disable them, resulting in pawns eternally meditating. Yet this mod forces this trait into default xenotypes.

**Comment by vegapnk** [comment]
Hi @Stars22223 , thanks for reaching out to me :) 

1. is no problem, I just don't exactly know how :P Some people tell me that I should only use the About.xml, some only the Manifest.xml so I was a bit confused. For me things show up in the ingame-mod manager correctly. 
2. Maybe something is not working properly for you, but in theory all genes that really need another mod (e.g. licentia when it comes to cumflation) are already invisible / not active for users without the respective mod. it is possible for pawns to gain fertilin based on the abilities and normal rjw interaction, but maybe it is a bit difficult (I think I nerfed need with 1.3 and I added another gene for gaining fertilin passively)
3. I don't know what is conflicting, when I tested things animal inheritance works with base-game + rjw. If you have any issues please let me know. There is an issue when using Menstruation #67, but that is not base-rjw 

1A) Yes that was intended. They seem to work, as the important thing about the genes is the order in which they are applied. The sex-change must be done before the genitalia-changes. The AG ones seem to be fine, but I have my own as not everyone uses AG. It is a bit of bloat indeed. 
2B) I have not perceived hypersexuality to be broken, but I will consider removing it from the Highmates 👍 

Thank you for your perspective again. Most users seem to have a lot of mods and most of the RJW mods. So it is nice to hear the perspective of someone that does not use all rjw mods.

**Comment by vegapnk** [comment]
I think by now most of the feedback has moved in :)
