### ISSUE TITLE
Succubus Tail and Wings texture mispathed

### ISSUE THREAD

**Issue by CryoRenegade** [vegapnk/RJW-Genes#73]
AS stated in the title, the succubus textures are missing in the game due to a mismatch with the supplied paths.
Convo started here: [](https://discord.com/channels/374305025486225409/374305025486225417/1172651837749473361)

Looks like the GeneDefs_Cosmetic has uppercase words in the path where its not needed.

**Comment by vegapnk** [comment]
Should be fixed with 2.0.0 

Still very much thank you for your PR #74 nananan <3 I am a bad maintainer
