### ISSUE TITLE
Genital genes

### ISSUE THREAD

**Issue by Greendasteel** [vegapnk/RJW-Genes#78]
i tryed to change genitals gene by my self replacing "generic" anuses and vaginas to human ones and failed...
changed all source code to "average_genitalia" but still end up with animalistic genitals and generic anus...
p.s what i done wrong? and i dont like to use animal vags and generic anuses due they more placeholder than actual genitalia
my rimworld heavily based on rimnude visuals so genitalia a drawn on pawn. and replacing every vag and anus after applying genes anoying and time spending...
p.p.s if somebody still check that GIT pls help me replacing "generic" anuses and vagina to human regular ones in genitalia genes. i need only "pencils"

**Comment by Greendasteel** [comment]
to be specific i change that line from Gene_AnimalGenitalia.cs
GenitaliaChanger.ChangeGenitalia(this.pawn,Genital_Helper.canine_penis,Genital_Helper.average_vagina(was canin),Genital_Helper.average_anus(was generic));
ofcource i done it for second line too and in all Gene_animalGenitalia.cs files and donr some changes in GeneUtility.cs

**Comment by vegapnk** [comment]
Should be fixed / included with 2.0.0
