### ISSUE TITLE
Big breast gene 

### ISSUE THREAD

**Issue by Cookiecrumblesss** [vegapnk/RJW-Genes#8]
EDIT: added “(core)” to “main”.

Breast size seem to be random when applying the big breasts gene. Pawns still get small or tiny breasts. 

Test modlist:

- harmony
- Main (Core)
- All DLC
- hugslib
- Rjw
- Rjw genes

**Comment by vegapnk** [comment]
Thanks for the Report! 

I will look into this. 

Can you maybe specify where you found Non-Big-Tiddie Pawns? 
On Colony-Creation, Guests, Spawned Children, Gene-Added later In-Game ? 

Tbh what I tested was adding Gene in-game and on Colony. That seemed to work nicely.

**Comment by Cookiecrumblesss** [comment]
> Thanks for the Report!
> 
> I will look into this.
> 
> Can you maybe specify where you found Non-Big-Tiddie Pawns? On Colony-Creation, Guests, Spawned Children, Gene-Added later In-Game ?
> 
> Tbh what I tested was adding Gene in-game and on Colony. That seemed to work nicely.

Hey, thanks for the reply!

on colony creation when making and applying the xenotype and adding the genes in game trough dev options I get the randoms. Can’t tell about the guests or spawns for I haven’t tested it. 

It’s on a clean install and latest mod-versions are used in the test modlist btw.

**Comment by IDAZIZ** [comment]
I would like to report a similar problem.

when my pawns give birth to their babies and reach adulthood, the breasts remain small.

I selected the parents xenotype using "character editor" then applied and saved, this way worked for me.

**Comment by vegapnk** [comment]
> and reach adulthood, the breasts remain small.

I can see where that is coming from! I will make a new Issue and try to fix it soon. 

Issue is that RJW adds Genitalia on birth, but ... effectively they are disabled (rightfully so). So my Genes trigger too early.

**Comment by vegapnk** [comment]
I hope this is addressed alongside #11, re-open if persists.
