### ISSUE TITLE
Licentia Labs Elasticity Gene doesn't work

### ISSUE THREAD

**Issue by SirPlebeian** [vegapnk/RJW-Genes#87]
I get an error anytime I try to use or apply the Elasticity Gene to any pawn, normally or via Character Editor. Additionally, on startup I have an error message saying that it "could not find a type named RJW_Genes.Genes_Elasticity"

**Comment by vegapnk** [comment]
Thanks for the repor :) Yes I can see that happening, I will try to address this soon.

**Comment by SirPlebeian** [comment]
I'm new to RJW mods so I didn't realize I was using a forked version of licentia mods. but your changes worked, thank you.
