### ISSUE TITLE
Sexual Tamer Gene Breaks Bestiality

### ISSUE THREAD

**Issue by SirPlebeian** [vegapnk/RJW-Genes#92]
Had an issue coming up recently with newest update where pawns attempting bestiality will begin the act just fine, but stop halfway through and then will attempt to repeat several times before giving up. I think I've narrowed down the issue to the Sexual Tamer gene because as soon as I remove it from the pawn bestiality works fine again. 

Can confirm that the bug only occurs when a sexual tamer attempts bestiality with a tamed creature that either: 
1) That is fully trained on everything, OR
2) The pawn runs out of things you are attempting to train them in. For example, the bug will still occur even if you leave "haul" untrained, as long as the animal is not attempting to learn it.

The error message is:
Exception in JobDriver tick for pawn Xochitl driver=JobDriver_BestialityForFemale (toilIndex=5) driver.job=(BestialityForFemale (Job_156069) A = Thing_Wolf_Timber67685 B = Thing_SleepingSpot50354 Giver = ThinkNode_QueuedJob [workGiverDef: null])

**Comment by vegapnk** [comment]
Added another null-check, should be fixed in 2.1.0
