### ISSUE TITLE
Request: Extend VE Genetics support

### ISSUE THREAD

**Issue by SirPlebeian** [vegapnk/RJW-Genes#93]
To be more specific:
1) Allow animal hybridization as well. Currently support is only for animal/human hybrids, but what about "bearwolf" for example?
2) Add spectrums to hybridization. Currently if VE Genetics is enabled for genes, children will _always_ be a hybrid. But maybe you can make it so that there is a spectrum between "vanilla" births and "hybrid" births so it's not an either/or.

Probably a side note but:
I took a look at the defs for the compatibility patch. I'm still new to modding, but currently it is hard coded for each individual breeding pair for what it should result in. Which is fine. But couldn't it be possible to first categorize animals based on their "core"? I.e. wolf, timber wolf, and warg could be fit into a master group called "canine" and then use "canine" to determine what resulting children will be for all three. Sort of like how rjw handles animal genatalia. Would be a lot easier for me to make a patch myself for modded creatures not supported such as Medieval Overhaul.

**Comment by vegapnk** [comment]
I will close this for now but I have not forgotten. 

The thing is I believe this would be best as a separate mod.
